from enum import IntEnum

MAP_SIZE = 48
ROBOT_ACTIONS = 13
FACTORY_ACTIONS = 3
GIV_SIZE = 33
IMG_FEATURES_SIZE = 31
FACTORY_VEC = 8
UNIT_VEC = 7

class RobotAction(IntEnum):	
	MOVE = 0
	TRANSFER = 1
	PICKUP = 2
	DIG = 3
	SELF_DESTRUCT = 4
	RECHARGE = 5

class FactoryAction(IntEnum):
	BUILD_LIGHT = 0
	BUILD_HEAVY = 1
	WATER = 2